import { Category, Product } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Filature & Fils Industriels",
    slug: "filature",
    description: "Fils 100% coton peigné, polyester haute ténacité et mélanges techniques pour tissage et tricotage.",
    count: 24,
  },
  {
    id: "cat-2",
    name: "Tissus d'Ameublement & Déco",
    slug: "ameublement",
    description: "Jacquards d'exception, velours soyeux et toiles texturées pour rideaux, sièges et hôtellerie.",
    count: 38,
  },
  {
    id: "cat-3",
    name: "Mailles & Tricotage Circulaire",
    slug: "mailles",
    description: "Jersey fin, interlock, molleton gratté et piqué pour confection de vêtements de sport et mode.",
    count: 31,
  },
  {
    id: "cat-4",
    name: "Gamme Éco-responsable & Bio",
    slug: "eco-responsable",
    description: "Fibres certifiées GOTS, lin normand lavé, coton recyclé et teintures végétales sans métaux lourds.",
    count: 19,
  },
  {
    id: "cat-5",
    name: "Textiles Techniques & Pro",
    slug: "techniques",
    description: "Tissus déperlants, ignifugés M1, antibactériens et haute résistance pour le médical et l'industrie.",
    count: 15,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Satin de Coton d'Égypte 120 Fil",
    reference: "SAT-EGY-400",
    slug: "satin-coton-egypte-120",
    description: "Tissu d'une douceur satinée remarquable, tissé avec des fibres extra-longues de coton égyptien. Idéal pour le linge de lit de prestige des palaces et la confection haut de gamme.",
    composition: "100% Coton d'Égypte peigné longues fibres",
    grammage: 135,
    width: 280,
    usage: "Linge de lit de luxe, Hôtellerie 5 étoiles, Chemiserie",
    certifications: ["OEKO-TEX Standard 100", "GOTS Certified", "Origine Égypte"],
    colors: ["#FFFFFF", "#F4F1EA", "#D4C7B5", "#2B3A42", "#8E9AA0"],
    imageUrl: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop",
    featured: true,
    minOrderMeters: 50,
    inStock: true,
    categoryId: "cat-1",
    categoryName: "Filature & Fils Industriels",
    technicalSpecs: {
      weaveType: "Satin 4/1",
      yarnCount: "Ne 60/1 x Ne 60/1",
      shrinkage: "< 1.5% à 60°C",
      washingTemp: "60°C - Blanchiment autorisé pour le blanc",
    },
  },
  {
    id: "prod-2",
    name: "Toile de Lin Normand Pur Lavé",
    reference: "LIN-NOR-280",
    slug: "toile-lin-normand-pur-lave",
    description: "Lin authentique cultivé en Normandie, adouci mécaniquement sans traitement chimique nocif. Son tombé fluide et son froissé naturel apportent un charme intemporel aux intérieurs contemporains.",
    composition: "100% Lin européen certifié Masters of Linen",
    grammage: 220,
    width: 145,
    usage: "Rideaux, Canapés, Coussins, Linge de table, Vêtements d'été",
    certifications: ["European Flax", "OEKO-TEX Class 1", "Masters of Linen"],
    colors: ["#E3DAC9", "#C2B280", "#A89F91", "#4A5859", "#78281F"],
    imageUrl: "https://images.unsplash.com/photo-1606857521015-7f9fcf423740?q=80&w=1000&auto=format&fit=crop",
    featured: true,
    minOrderMeters: 25,
    inStock: true,
    categoryId: "cat-2",
    categoryName: "Tissus d'Ameublement & Déco",
    technicalSpecs: {
      weaveType: "Armure Toile",
      yarnCount: "Nm 26/1",
      shrinkage: "< 2% (déjà pré-lavé)",
      washingTemp: "40°C programme délicat",
    },
  },
  {
    id: "prod-3",
    name: "Jacquard Vénitien Relief Arabesque",
    reference: "JAC-VEN-480",
    slug: "jacquard-venitien-relief",
    description: "Tissage jacquard complexe mariant fils mats de coton et trame soyeuse en viscose pour un jeu de reflets subtil. Haute résistance au frottement pour usage intensif en tapisserie d'ameublement.",
    composition: "55% Coton, 35% Viscose, 10% Polyester",
    grammage: 460,
    width: 140,
    usage: "Fauteuils club, Sièges d'accueil, Têtes de lit, Panneaux muraux",
    certifications: ["OEKO-TEX Standard 100", "Martindale 45 000 tours"],
    colors: ["#2C3E50", "#B38F4E", "#8A1C14", "#1E272C"],
    imageUrl: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1000&auto=format&fit=crop",
    featured: true,
    minOrderMeters: 20,
    inStock: true,
    categoryId: "cat-2",
    categoryName: "Tissus d'Ameublement & Déco",
    technicalSpecs: {
      weaveType: "Jacquard double nappe",
      yarnCount: "Ne 20/2 x Ne 30/2",
      shrinkage: "< 1%",
      washingTemp: "Nettoyage à sec recommandé",
    },
  },
  {
    id: "prod-4",
    name: "Jersey Coton Bio Peigné & Élasthanne",
    reference: "JER-BIO-210",
    slug: "jersey-coton-bio-elasthanne",
    description: "Maille tricotée fine et respirante avec une excellente élasticité et tenue dimensionnelle après lavages fréquents. Teinture à l'eau réactive sans solvants.",
    composition: "95% Coton biologique GOTS, 5% Élasthanne Roica",
    grammage: 210,
    width: 160,
    usage: "T-shirts haut de gamme, Vêtements bébé, Lingerie, Sportswear",
    certifications: ["GOTS Organic", "OEKO-TEX Standard 100 - Annexe 6"],
    colors: ["#111111", "#F8F9FA", "#3B4252", "#D08770", "#A3BE8C"],
    imageUrl: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=1000&auto=format&fit=crop",
    featured: true,
    minOrderMeters: 50,
    inStock: true,
    categoryId: "cat-3",
    categoryName: "Mailles & Tricotage Circulaire",
    technicalSpecs: {
      weaveType: "Single Jersey circulaire Jauge 28",
      yarnCount: "Ne 30/1 peigné",
      shrinkage: "< 3%",
      washingTemp: "40°C en machine",
    },
  },
  {
    id: "prod-5",
    name: "Sergé Technique Hydrofuge & Déperlant M1",
    reference: "TEC-HYD-340",
    slug: "serge-technique-hydrofuge-m1",
    description: "Tissu technique haute ténacité doté d'un traitement déperlant hydrophobe sans fluorocarbone et homologué non feu M1 pour les ERP (Établissements Recevant du Public).",
    composition: "80% Polyester Trévira CS, 20% Coton enduit",
    grammage: 340,
    width: 150,
    usage: "Collectivités, Hôtellerie, Aéroports, Terrasses couvertes, Housse pro",
    certifications: ["Norme Feu M1 / B1", "OEKO-TEX", "Déperlant Eco-PFC Free"],
    colors: ["#1A252C", "#34495E", "#7F8C8D", "#2C3E50"],
    imageUrl: "https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?q=80&w=1000&auto=format&fit=crop",
    featured: false,
    minOrderMeters: 100,
    inStock: true,
    categoryId: "cat-5",
    categoryName: "Textiles Techniques & Pro",
    technicalSpecs: {
      weaveType: "Sergé 2/2 renforcé",
      yarnCount: "Dtex 330/2",
      shrinkage: "< 0.5%",
      washingTemp: "40°C essorage doux",
    },
  },
  {
    id: "prod-6",
    name: "Filature Coton Peigné Ne 30/1 & 40/2",
    reference: "FIL-COT-100",
    slug: "filature-coton-peigne-industriel",
    description: "Bobines industrielles coniques de fil 100% coton peigné pour métiers à tisser grande vitesse et machines à tricoter rectilignes ou circulaires. Ténacité uniforme et faible taux de pilosité.",
    composition: "100% Coton peigné longue soie",
    grammage: 100,
    width: 0,
    usage: "Tissage chaîne & trame, Tricotage maille, Confection industrielle",
    certifications: ["OEKO-TEX Standard 100", "ISO 9001:2015"],
    colors: ["#F9F9F9", "#EFEFEF", "#DCDCDC"],
    imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=1000&auto=format&fit=crop",
    featured: false,
    minOrderMeters: 500,
    inStock: true,
    categoryId: "cat-1",
    categoryName: "Filature & Fils Industriels",
    technicalSpecs: {
      weaveType: "Fil simple ou retors sur cône de 2.5 kg",
      yarnCount: "Ne 30/1, 40/2, 50/2 disponibles",
      shrinkage: "N/A",
      washingTemp: "Standard industriel",
    },
  },
  {
    id: "prod-7",
    name: "Velours de Coton Côtelé Royal 8 Wales",
    reference: "VEL-ROY-390",
    slug: "velours-coton-cotele-royal",
    description: "Velours côtelé lourd aux côtes généreuses et au toucher douillet d'une élégance vintage incomparable. Idéal pour manteaux, vestes d'architecte, coussins d'assise et tapisserie feutrée.",
    composition: "100% Coton biologique peigné",
    grammage: 390,
    width: 145,
    usage: "Prêt-à-porter automne/hiver, Coussins de banquette, Fauteuils",
    certifications: ["GOTS Certified", "OEKO-TEX Class 1"],
    colors: ["#4A3728", "#223A2C", "#1F2937", "#8C6239", "#A84234"],
    imageUrl: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=1000&auto=format&fit=crop",
    featured: true,
    minOrderMeters: 30,
    inStock: true,
    categoryId: "cat-2",
    categoryName: "Tissus d'Ameublement & Déco",
    technicalSpecs: {
      weaveType: "Velours trame côtelé 8 côtes / pouce",
      yarnCount: "Ne 20/2 x Ne 16/1",
      shrinkage: "< 2%",
      washingTemp: "30°C sur l'envers",
    },
  },
  {
    id: "prod-8",
    name: "Molleton Coton Gratté Chaud 320g",
    reference: "MOL-GRA-320",
    slug: "molleton-coton-gratte-chaud",
    description: "Maille molleton 3 fils avec face envers grattée ultra-moelleuse et face endroit lisse idéale pour la sérigraphie et la broderie de précision. Très grande durabilité.",
    composition: "85% Coton biologique, 15% Polyester recyclé",
    grammage: 320,
    width: 180,
    usage: "Sweat-shirts, Hoodies streetwear, Pantalons détente, Plaids",
    certifications: ["GOTS Organic", "GRS (Global Recycled Standard)"],
    colors: ["#2E3440", "#D8DEE9", "#4C566A", "#5E81AC"],
    imageUrl: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1000&auto=format&fit=crop",
    featured: false,
    minOrderMeters: 40,
    inStock: true,
    categoryId: "cat-3",
    categoryName: "Mailles & Tricotage Circulaire",
    technicalSpecs: {
      weaveType: "Molleton 3 fils jauge 20",
      yarnCount: "Ne 30/1 + 20/1 + 10/1",
      shrinkage: "< 3% au séchage naturel",
      washingTemp: "30°C ou 40°C",
    },
  },
];
